# Generated by Django 2.0.6 on 2019-04-17 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='State',
            fields=[
                ('statid', models.AutoField(primary_key=True, serialize=False)),
                ('statename', models.CharField(default='', max_length=255, unique=True)),
            ],
        ),
    ]
