# Generated by Django 3.0.3 on 2020-02-15 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Packages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('description', models.TextField()),
                ('price', models.FloatField()),
                ('discount_price', models.FloatField()),
                ('payment_option', models.CharField(choices=[('online', 'online'), ('offline', 'offline'), ('both', 'both')], max_length=20)),
            ],
        ),
    ]
