# Generated by Django 3.0.3 on 2020-02-15 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='packages',
            name='slug',
            field=models.SlugField(blank=True, default=None, max_length=40, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='packages',
            name='name',
            field=models.CharField(max_length=40, unique=True),
        ),
    ]
