# Generated by Django 3.0.3 on 2020-02-17 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_auto_20200215_2034'),
    ]

    operations = [
        migrations.AddField(
            model_name='packages',
            name='option_1',
            field=models.CharField(blank=True, default=None, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='packages',
            name='option_2',
            field=models.CharField(blank=True, default=None, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='packages',
            name='option_3',
            field=models.CharField(blank=True, default=None, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='packages',
            name='option_4',
            field=models.CharField(blank=True, default=None, max_length=120, null=True),
        ),
    ]
