# Generated by Django 3.0.3 on 2020-02-20 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_auto_20200217_2052'),
    ]

    operations = [
        migrations.AddField(
            model_name='packages',
            name='static_img_route',
            field=models.CharField(blank=True, default=None, max_length=120, null=True),
        ),
    ]
