# Generated by Django 3.0.3 on 2020-02-20 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0004_packages_static_img_route'),
    ]

    operations = [
        migrations.AddField(
            model_name='packages',
            name='minimum_attendants',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='packages',
            name='occurence',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='packages',
            name='starting_point',
            field=models.TextField(blank=True, default=None, null=True),
        ),
    ]
