# Generated by Django 3.0.3 on 2020-02-21 19:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0006_gallery'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gallery',
            old_name='alt',
            new_name='slug',
        ),
    ]
