# Generated by Django 3.0.3 on 2020-02-21 19:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0007_auto_20200221_2026'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gallery',
            name='slug',
        ),
    ]
