# Generated by Django 3.0.3 on 2020-02-15 18:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0001_initial'),
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('email', models.EmailField(max_length=254)),
                ('headcount', models.FloatField()),
                ('payment_type', models.CharField(choices=[('online', 'online'), ('offline', 'offline')], max_length=20)),
                ('payment_made', models.BooleanField(default=False)),
                ('invoice_sent', models.BooleanField(default=False)),
                ('sold_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='user.User')),
            ],
        ),
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coupon_name', models.CharField(max_length=50)),
                ('coupon_discount', models.FloatField()),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='user.User')),
            ],
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=60)),
                ('customer_email', models.EmailField(max_length=254)),
                ('headcount', models.FloatField(default=1)),
                ('customer_id', models.FloatField()),
                ('date', models.DateTimeField()),
                ('type_of_booking', models.CharField(choices=[('online', 'online'), ('offline', 'offline')], max_length=20)),
                ('terms_and_conditions_accepted', models.BooleanField(default=False)),
                ('package', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pages.Packages')),
                ('sold_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='user.User')),
            ],
        ),
    ]
