# Generated by Django 3.0.3 on 2020-02-16 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0004_customer_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='price',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
    ]
