# Generated by Django 3.0.3 on 2020-02-16 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0007_auto_20200216_1826'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='price',
        ),
        migrations.AddField(
            model_name='booking',
            name='price',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
    ]
