# Generated by Django 3.0.3 on 2020-02-16 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0008_auto_20200216_1900'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='date_string',
            field=models.CharField(blank=True, default=None, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='date',
            field=models.DateField(),
        ),
    ]
