# Generated by Django 3.0.3 on 2020-02-16 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0009_auto_20200216_1920'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='payment_made',
        ),
        migrations.AddField(
            model_name='booking',
            name='payment_made',
            field=models.BooleanField(default=False),
        ),
    ]
