# Generated by Django 3.0.3 on 2020-02-17 20:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0011_transaction'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaction',
            old_name='bt_transation_id',
            new_name='bt_transaction_id',
        ),
    ]
