# Generated by Django 3.0.3 on 2020-02-17 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0012_auto_20200217_2100'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='bt_transaction_id',
            field=models.CharField(max_length=60),
        ),
    ]
