# Generated by Django 3.0.3 on 2020-02-20 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0014_auto_20200217_2110'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='coupon_name',
            field=models.CharField(blank=True, default=None, max_length=60, null=True),
        ),
    ]
